// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementApp.Data;

#nullable disable

namespace ProductManagementApp.Data.Migrations
{
    [DbContext(typeof(PMDataContext))]
    [Migration("20230724011543_UpdateUserEntity")]
    partial class UpdateUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementApp.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Category", "Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Appetizer",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Dimsum",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "FireRice",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Noodle",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "All",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentSupplier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HistoryHighPrice")
                        .HasColumnType("float");

                    b.Property<double>("HistoryLowPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrimeCost")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UsageUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient", "Food");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04cc37d8-555a-4139-94f4-a2d26cacad4a"),
                            Brand = "NoName",
                            Code = "I001",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 14.0,
                            HistoryLowPrice = 12.0,
                            Name = "Salt",
                            PrimeCost = 14.0,
                            Quantity = 5.0,
                            Unit = "Kg",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        },
                        new
                        {
                            Id = new Guid("f8e9be1a-49f3-401a-9d5e-26926b18b730"),
                            Brand = "NoName",
                            Code = "I002",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 15.0,
                            HistoryLowPrice = 13.0,
                            Name = "Sugar",
                            PrimeCost = 15.0,
                            Quantity = 5.0,
                            Unit = "Kg",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        },
                        new
                        {
                            Id = new Guid("764ba3c5-ae6a-4ee2-be7d-bd69fe0f6462"),
                            Brand = "NoName",
                            Code = "I003",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 10.0,
                            HistoryLowPrice = 9.0,
                            Name = "Wheat Flour",
                            PrimeCost = 10.0,
                            Quantity = 5.0,
                            Unit = "Kg",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        },
                        new
                        {
                            Id = new Guid("63829485-1afd-4e21-910f-553363736493"),
                            Brand = "NoName",
                            Code = "I004",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 34.0,
                            HistoryLowPrice = 24.0,
                            Name = "Rice Noodle",
                            PrimeCost = 34.0,
                            Quantity = 30.0,
                            Unit = "lb",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        },
                        new
                        {
                            Id = new Guid("b59619f1-bae6-442a-a3f6-ef8487542a7b"),
                            Brand = "NoName",
                            Code = "I005",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 34.0,
                            HistoryLowPrice = 31.0,
                            Name = "Rice",
                            PrimeCost = 34.0,
                            Quantity = 30.0,
                            Unit = "kg",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        },
                        new
                        {
                            Id = new Guid("1e674b1e-db3f-4466-93d0-895832c43266"),
                            Brand = "NoName",
                            Code = "I006",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentSupplier = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            HistoryHighPrice = 45.0,
                            HistoryLowPrice = 40.0,
                            Name = "Soya",
                            PrimeCost = 45.0,
                            Quantity = 20.0,
                            Unit = "L",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsageUnit = "g"
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.IngredientTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IngredientList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("IngredientTemplate", "Food");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcda4b0c-dc6e-4644-bc95-bb21b3501c04"),
                            Category = 5,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Basic flavor",
                            IngredientList = "{\"04cc37d8-555a-4139-94f4-a2d26cacad4a\":5.0,\"f8e9be1a-49f3-401a-9d5e-26926b18b730\":3.0}",
                            Name = "flavor Base",
                            TotalCost = 0.0,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7f9ac754-d077-4818-9df3-2c23ef5a1c0e"),
                            Category = 2,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Basic ingredient of making buns",
                            IngredientList = "{\"04cc37d8-555a-4139-94f4-a2d26cacad4a\":5.0,\"f8e9be1a-49f3-401a-9d5e-26926b18b730\":30.0,\"764ba3c5-ae6a-4ee2-be7d-bd69fe0f6462\":200.0}",
                            Name = "Bun Base",
                            TotalCost = 0.0,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AppliedDiscount")
                        .HasColumnType("float");

                    b.Property<Guid>("Client")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("CreditAmount")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("DeliveryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ItemList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderAmount")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("StartingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Order", "Product");
                });

            modelBuilder.Entity("ProductManagementApp.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<double>("CostPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IngredientList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsContinuing")
                        .HasColumnType("bit");

                    b.Property<double>("ManHour")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("bit");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Product", "Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34e9683e-7421-4421-bcfe-15015391cc1e"),
                            Category = 2,
                            CostPrice = 1.2,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsContinuing = true,
                            ManHour = 1.0,
                            Name = "SpicyPork Bun",
                            OutOfStock = false,
                            SalePrice = 6.0,
                            Stock = 999,
                            Unit = "pack",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("1a96b935-0bdd-4a9f-98e9-d4be5dc1146e"),
                            Category = 1,
                            CostPrice = 4.2999999999999998,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsContinuing = true,
                            ManHour = 1.0,
                            Name = "Sweet Wings",
                            OutOfStock = false,
                            SalePrice = 8.0,
                            Stock = 999,
                            Unit = "pack",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("88e708ac-47a9-4dab-aaf4-d75b2e1a039e"),
                            Category = 4,
                            CostPrice = 5.5,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsContinuing = true,
                            ManHour = 1.0,
                            Name = "ShangHai Fire Noodle",
                            OutOfStock = false,
                            SalePrice = 9.0,
                            Stock = 999,
                            Unit = "each",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9d37e8bd-c979-4b47-9c87-0a530e0c19a0"),
                            Category = 3,
                            CostPrice = 3.5,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsContinuing = true,
                            ManHour = 1.0,
                            Name = "Beef Rice",
                            OutOfStock = false,
                            SalePrice = 8.0,
                            Stock = 999,
                            Unit = "each",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0568983b-5e73-49cf-9829-544e49febb2e"),
                            Category = 1,
                            CostPrice = 1.8999999999999999,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsContinuing = true,
                            ManHour = 1.0,
                            Name = "Mix Vegetable Soup",
                            OutOfStock = false,
                            SalePrice = 3.5,
                            Stock = 999,
                            Unit = "each",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Role", "AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "SysAdmin",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Merchant",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Supplier",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Customer",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalesName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Supplier", "Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bf9df1a-26a5-4852-9f45-94f1d6c0131e"),
                            Address = "4588 104St SE, Edmonton, AB",
                            CompanyName = "WangDa Wholesale",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "wdwhole@yahoo.com",
                            Phone = "(780)445-1458",
                            SalesName = "Alex",
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ProductManagementApp.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("User", "AppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da4153e9-c1b1-44e3-a180-78e6c4dcf276"),
                            Address = "P.O. Box 869, 6283 Lorem Av.",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "libero.proin@yahoo.net",
                            FirstName = "Gavin",
                            LastName = "Poole",
                            MiddleName = "",
                            Password = "abcde12345",
                            Phone = "(878) 577-3238",
                            Role = 2,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "GPuser878"
                        },
                        new
                        {
                            Id = new Guid("9b32a9ed-dea3-4091-9e47-94bfa929bf49"),
                            Address = "891-3948 Dapibus Rd.",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "mauris@google.org",
                            FirstName = "Ronan",
                            LastName = "Carr",
                            MiddleName = "",
                            Password = "abcde12345",
                            Phone = "(884) 803-7319",
                            Role = 2,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "RCuser884"
                        },
                        new
                        {
                            Id = new Guid("4b109af5-f84a-45f9-b5da-15b66e59a8df"),
                            Address = "568-6361 Hendrerit Av.",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sed@google.edu",
                            FirstName = "Kitra",
                            LastName = "Winters",
                            MiddleName = "",
                            Password = "abcde12345",
                            Phone = "(206) 937-9022",
                            Role = 2,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "KWuser206"
                        },
                        new
                        {
                            Id = new Guid("e8718d0d-d31a-48c3-903b-162d1c7a2d12"),
                            Address = "Ap #679-5023 Adipiscing Road",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dictum.cursus@hotmail.com",
                            FirstName = "Unity",
                            LastName = "House",
                            MiddleName = "",
                            Password = "abcde12345",
                            Phone = "(332) 471-1352",
                            Role = 2,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "UHuser206"
                        },
                        new
                        {
                            Id = new Guid("c5e099e8-bebe-4249-a7e4-56b55d553d9d"),
                            Address = "Ap #679-5023 Adipiscing Road",
                            CreatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sam.zhu992@yahoo.com",
                            FirstName = "Sam",
                            LastName = "Zhu",
                            MiddleName = "",
                            Password = "abcde12345",
                            Phone = "(992) 471-1352",
                            Role = 1,
                            UpdatedBy = new Guid("4af36f59-a750-4d33-ab0a-c29e59defe11"),
                            UpdatedDate = new DateTimeOffset(new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "SZuser992"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
